name: Aviso de modos
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  avisar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python avisar.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
